
name: Second Wave Screener

on:
  schedule:
    - cron: "7 * * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run screener
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          COIN_IDS: ${{ secrets.COIN_IDS }}
          H24_MIN:  ${{ secrets.H24_MIN }}
          H1_MIN:   ${{ secrets.H1_MIN }}
          H1_MAX:   ${{ secrets.H1_MAX }}
          TOPK:     ${{ secrets.TOPK }}
          VOL24_MIN: ${{ secrets.VOL24_MIN }}
          PB_H24_MIN: ${{ secrets.PB_H24_MIN }}
          PB_H1_MIN:  ${{ secrets.PB_H1_MIN }}
          PB_H1_MAX:  ${{ secrets.PB_H1_MAX }}
        run: |
          python screener.py
